import Head from "next/head";

import { useState } from "react";

import Image from "next/image";

import userData from "../constant/data";
import LatestCode from "@/components/LatestCode";
import getLatestRepos from "@/lib/getLatestRepo";
import Navbar from "@/components/Navbar";
import About from "@/components/About";
import Projects from "@/components/Projects";
import Experience from "@/components/Experience";

export default function Home({ repositories }) {
  const [darkMode, setDarkMode] = useState(false);
  const [open, setOpen] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white">
        <Navbar />
        <About />
        <Projects />
        <Experience />
        <LatestCode repositories={repositories} />
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  let token = process.env.GITHUB_AUTH_TOKEN;

  const repositories = await getLatestRepos(userData, token);

  return {
    props: {
      repositories,
    },
  };
};
